coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_head: no
  require_base: no
