version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:14'
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: commitlint
          command: npx --no-install commitlint-circle
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test
      - run:
          name: build
          command: npm run build
      - run:
          name: release
          command: npm run semantic-release