version: 2.1

orbs:
  codecov: codecov/codecov@3.1.0

workflows:
  build-workflow:
    jobs:
      - build:
          context:
            - deployment
      - coverage

jobs:
  build:
    docker:
      - image: cimg/node:14.19.3
    environment:
      ENV_NAME: ci
    steps:
      - checkout
      - run:
          name: install
          command: NODE_ENV=$ENV_NAME npm ci
      - run:
          name: commitlint
          command: npx --no-install commitlint-circle
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: NODE_ENV=$ENV_NAME npm run test
      - run:
          name: build
          command: NODE_ENV=$ENV_NAME npm run build
      - run:
          name: release
          command: NODE_ENV=$ENV_NAME npm run semantic-release
  coverage:
    docker:
      - image: cimg/node:14.19.3
    environment:
      ENV_NAME: ci
    steps:
      - checkout
      - run:
          name: install
          command: NODE_ENV=$ENV_NAME npm ci
      - run:
          name: coverage
          command: NODE_ENV=$ENV_NAME npm run coverage
      - codecov/upload

