version: 2.1

orbs:
  codecov: codecov/codecov@3.1.0

workflows:
  build-workflow:
    jobs:
      - build:
          context:
            - deployment
      - coverage

jobs:
  build:
    docker:
      - image: 'circleci/node:14'
    steps:
      - checkout
      - run:
          name: install
          command: npm ci
      - run:
          name: commitlint
          command: npx --no-install commitlint-circle
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test
      - run:
          name: build
          command: npm run build
      - run:
          name: release
          command: npm run semantic-release
  coverage:
    docker:
      - image: 'circleci/node:14'
    steps:
      - checkout
      - run:
          name: install
          command: npm ci
      - run:
          name: coverage
          command: npm run coverage
      - codecov/upload

